# Generated by Django 4.0.3 on 2022-06-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='departname')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='realname')),
                ('pwd', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('account', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance')),
                ('create_time', models.DateTimeField(verbose_name='createdate')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManaSys.department')),
            ],
        ),
    ]
