# Generated by Django 4.0.5 on 2022-06-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManaSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unm', models.CharField(max_length=16, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='personnel',
            name='account',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManaSys.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='pwd',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
    ]
